### ISSUE TITLE
Image and JSON dataset.

### ISSUE THREAD

**Issue by Makefunof** [MMMU-Benchmark/MMMU#13]
Thanks for your great work! I want to use your data to train a model and I wonder how to transform the parquet dataset format into images and JSON file. Thanks in advance!

**Comment by xiangyue9607** [comment]
Hi,

Thanks for your interest! Our dataset was not intended for training purposes. All the data samples are for evaluation purposes only. For the dataset format conversion, you might load using hf datasets and then export it into json format. 

Thanks,
Xiang

**Comment by Makefunof** [comment]
Many thanks for you detailed reply！I am still wonder how to get all the image file for evaluation. Thanks again！

**Comment by xiangyue9607** [comment]
You can just load it from HF datasets.

From: make fun ***@***.***>
Date: Thursday, January 4, 2024 at 5:24 PM
To: MMMU-Benchmark/MMMU ***@***.***>
Cc: Xiang Yue ***@***.***>, Comment ***@***.***>
Subject: Re: [MMMU-Benchmark/MMMU] Image and JSON dataset. (Issue #13)
Many thanks for you detailed reply！I am still wonder how to get all the image file for evaluation. Thanks again！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented. Message ID: 


Many thanks for you detailed reply！I am still wonder how to get all the image file for evaluation. Thanks again！

**Comment by Makefunof** [comment]
Thank you very much！ How can I get the answer to the test files?

**Comment by xiangyue9607** [comment]
We did not release the test labels. You can submit your eval results in eval.ai: https://eval.ai/web/challenges/challenge-page/2179/overview

From: make fun ***@***.***>
Date: Thursday, January 4, 2024 at 11:14 PM
To: MMMU-Benchmark/MMMU ***@***.***>
Cc: Xiang Yue ***@***.***>, Comment ***@***.***>
Subject: Re: [MMMU-Benchmark/MMMU] Image and JSON dataset. (Issue #13)
Thank you very much！ How can I get the answer to the test files? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented. Message ID: <MMMU-Benchmark/MMMU/issues/13/1877258771@ github. com>


Thank you very much！ How can I get the answer to the test files?

**Comment by Makefunof** [comment]
Thanks!
