### ISSUE TITLE
process_single_sample function's question

### ISSUE THREAD

**Issue by bruceisme** [MMMU-Benchmark/MMMU#16]
A little confused about this part of the code. The comment means that when an image appears in the options, the image is set to None. But the way images appear in the data options is always as <image_x>, <img='(.*?) '> can't match anything.
https://github.com/MMMU-Benchmark/MMMU/blob/4ae8bf51ec7b3757d9a391504673ff6cd67c8d5b/eval/utils/data_utils.py#L83-L100

**Comment by drogozhang** [comment]
Hi,

Thanks for your interest. You are correct if there's an image on the option the image path (and image) would be set as None, because that means all options are images and all open-sourced models evaluated with this code, **can only take one image as input**. Therefore, for multiple images in the options, we do text-only for open-sourced LMMs.
For multiple images in the question part, we use the first image as main image as input.

Thanks for the great catch about the regex of parsing image path part. Due to the time of code development is before the huggingface upload, we have some mismatch. I will fix this when I have time.

Let me know if there's any other questions.

Best,
Kai

**Comment by drogozhang** [comment]
Close for inactivity, feel free to re-open it if you have further questions.

**Comment by MalvinaNikandrou** [comment]
Hi,

Could you clarify this a bit further? Does this mean that for open-source VLMs 

- in the input, there is only one image(the first image)
- the options are either text or None?

Thank you :)

**Comment by drogozhang** [comment]
Both of your statements are correct, **for open-source VLMs at the time we evaluate (2023 Nov)**.
Now more and more open-source VLMs can support multi-image inputs, so the options are either text or None.

We didn't have the inference code here as these model developers prefer to evaluate their models on MMMU with their own inference and prompt design. Thank you.

**Comment by MalvinaNikandrou** [comment]
Thank you for the clarification!
