### ISSUE TITLE
PNG files does not convert to RGB

### ISSUE THREAD

**Issue by y-vectorfield** [MMMU-Benchmark/MMMU#17]
I used this benchmark to measure performance of LLaVA.
The following warning message appeared.

```python
/usr/local/lib/python3.10/dist-packages/PIL/Image.py:981: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
```

I think image files did not convert to RGB type image files.

**Comment by drogozhang** [comment]
Hi,

Thanks for your question. The model needs the RGB format input so that's why we convert it so. The 'A' in RGBA is merely the alpha number showing the degree of transparent, which will not affect the later processing.

Hope it helps.

Best,
Kai

**Comment by y-vectorfield** [comment]
@drogozhang , thank you for your message.
Did the images convert to RGB from RGBA?
Does this mean this warning message is appearing because the A channel is deleted by conversion?

**Comment by drogozhang** [comment]
Yes, but that would not cause any problems because most LMMs (including llava here) need [RGB] images as input. So ignoring A channel is necessary and totally fine.

Some images may have transparent parts: [google logo](https://www.cleanpng.com/png-google-logo-2280160/) and converting it to RGB will just make the transparent parts be white. There will be no difference for image understanding of models.

**Comment by drogozhang** [comment]
You can recheck the image processing part of llava and run the MMMU on their code to see if their image processing will do the same conversion.

As authors of a benchmark, we are consistent with the image processing methods used by original models when evaluating them.
